// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: latest/test-lagi.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TestRequestLagi with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TestRequestLagi) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestRequestLagi with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestRequestLagiMultiError, or nil if none found.
func (m *TestRequestLagi) ValidateAll() error {
	return m.validate(true)
}

func (m *TestRequestLagi) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for UserID

	if len(errors) > 0 {
		return TestRequestLagiMultiError(errors)
	}

	return nil
}

// TestRequestLagiMultiError is an error wrapping multiple validation errors
// returned by TestRequestLagi.ValidateAll() if the designated constraints
// aren't met.
type TestRequestLagiMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestRequestLagiMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestRequestLagiMultiError) AllErrors() []error { return m }

// TestRequestLagiValidationError is the validation error returned by
// TestRequestLagi.Validate if the designated constraints aren't met.
type TestRequestLagiValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestRequestLagiValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestRequestLagiValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestRequestLagiValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestRequestLagiValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestRequestLagiValidationError) ErrorName() string { return "TestRequestLagiValidationError" }

// Error satisfies the builtin error interface
func (e TestRequestLagiValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestRequestLagi.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestRequestLagiValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestRequestLagiValidationError{}

// Validate checks the field values on TestResponseLagi with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TestResponseLagi) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestResponseLagi with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestResponseLagiMultiError, or nil if none found.
func (m *TestResponseLagi) ValidateAll() error {
	return m.validate(true)
}

func (m *TestResponseLagi) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return TestResponseLagiMultiError(errors)
	}

	return nil
}

// TestResponseLagiMultiError is an error wrapping multiple validation errors
// returned by TestResponseLagi.ValidateAll() if the designated constraints
// aren't met.
type TestResponseLagiMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestResponseLagiMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestResponseLagiMultiError) AllErrors() []error { return m }

// TestResponseLagiValidationError is the validation error returned by
// TestResponseLagi.Validate if the designated constraints aren't met.
type TestResponseLagiValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestResponseLagiValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestResponseLagiValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestResponseLagiValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestResponseLagiValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestResponseLagiValidationError) ErrorName() string { return "TestResponseLagiValidationError" }

// Error satisfies the builtin error interface
func (e TestResponseLagiValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestResponseLagi.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestResponseLagiValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestResponseLagiValidationError{}
